### ISSUE TITLE
Can join chanel from android app?

### ISSUE THREAD

**Issue by lordmen99** [AgoraIO/Agora-Word-Press#32]
I try join channel from open live demo app, where i have build with same appid. start streaming from post wordpress, but in android app, i cant see streaming. how we can join chanel streaming from web post then other user join from their mobile phone??

**Comment by digitallysavvy** [comment]
@lordmen99 when using the Agora Native and Web SDK's together you need to make sure to [enable WebSdk Interoperability.](https://docs.agora.io/en/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#a49636ee063476d7c3da533668771fa03)

```
mRtcEngine.enableWebSdkInteroperability(true);
```

This is enabled by default when using 
```
mRtcEngine.setChannelProfile(Constants.CHANNEL_PROFILE_COMMUNICATION);
```

but if you are using LiveBroadcasting mode then you have to enable WebSdk Interoperability.

**Comment by lordmen99** [comment]
ok,i remember that, but its in plugin option setting not add right? better add in setting too with optional

**Comment by digitallysavvy** [comment]
You only need to enable that on the Native SDK, there is no option for this within the WebSDK.

**Comment by lordmen99** [comment]
so, where mus add that option in the plugin? line code must add in this plugin

**Comment by digitallysavvy** [comment]
within the Android SDK you should enable it the line after you set the Channel Profile.

```
mRtcEngine.setChannelProfile(Constants.CHANNEL_PROFILE_LIVE_BROADCASTING);
mRtcEngine.enableWebSdkInteroperability(true); 
```

**Comment by lordmen99** [comment]
then in web app,specialy in this plugin where must add that option?

**Comment by digitallysavvy** [comment]
No where. This is only on native SDK.

**Comment by lordmen99** [comment]
i have try add in android app,still cant join channel when from web start streaming

**Comment by digitallysavvy** [comment]
I am able to replicate your issue using Agora's OpenLive Demo for Android. I'm working to figure out the cause of the issue and will update the ticket accordingly.

**Comment by lordmen99** [comment]
ok,thank you

**Comment by lordmen99** [comment]
any update?

**Comment by digitallysavvy** [comment]
Seems this may be related to an issue with the Android Open Live demo app https://github.com/AgoraIO/Basic-Video-Broadcasting/issues/45

**Comment by digitallysavvy** [comment]
@lordmen99 are you still experiencing this issue?
