### ISSUE TITLE
Screen Share not working in Chrome [BUG]

### ISSUE THREAD

**Issue by digitallysavvy** [AgoraIO/Agora-Word-Press#42]
**Describe the bug**
When clicking on the Share Screen icon in a group, Chrome gives the following error…

> AgoraRTCSDK-3.0.2.121.js:1 21:48:37:957 Agora-SDK [ERROR]: [547584703] Media access PluginNotInstalledProperly: No response from Chrome Plugin. Plugin not installed properly.

Also, the chat icon does not display at all when using the Agora.io Fullscreen template.

All ad blocker extensions disabled.

**To Reproduce**
1. open Agora channel (_communication/broadcasting_) in chrome browser
2. Click to start screen sharing 
3. See fail message

**Expected behavior**
1. open Agora channel (_communication/broadcasting_) in chrome browser
2. Click to start screen sharing 
3. See screen share

**Browser**
Chrome Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by qiuyanli1990** [comment]
Hello Sir,
For chrome 80 version you don't need the chrome plugin for screen sharing. You should uninstall chrome plugin and remove "extensionId: 'minllpmhdgpndnkomcoccfekfegnlikg'" in your screenStream.
Thanks!

**Comment by digitallysavvy** [comment]
@qiuyanli1990 thank you for your suggestion. We are working on resolving this issue.

**Comment by digitallysavvy** [comment]
@qiuchenglei I have uploaded my latest progress.

 I still need to do more testing, as this fix does not account for the user clicking the 'stop sharing' button that chrome overlays on the screen.

**Comment by digitallysavvy** [comment]
This issue has been resolved in v1.6.2 of the Agora Video for WordPress plugin

**Comment by tonyvugithub** [comment]
@digitallysavvy : Hi, I came across this issue and your comment is exactly what I have encountered, when I click on the 'stop sharing' button in chrome, it did not go back to my video stream but only when I click on the share button again then it did go back to video stream. I am using "agora-rtc-sdk": "^3.4.0" and here is my code for sharing screen. I am having my own mutation states for video and audio
![image](https://user-images.githubusercontent.com/55034244/118018877-57e9c780-b326-11eb-9f7e-3263d3b829d1.png)
